### ISSUE TITLE
Compilation error on Unix/Linux since Calibri is a Windows font.

### ISSUE THREAD

**Issue by tolribeiro** [dnl-blkv/mcdowell-cv#3]
Tried compiling the .tex on my Mac and got the error about the Calibri font, so I changed the .cls to a Unix-compatible one.

**Comment by dnl-blkv** [comment]
@tolribeiro Unfortunately, I have not currently got a mac for testing. Could you please suggest a font name and size suitable for Mac? I mean the ones saving the resume proportions. Would it work with 10.5pt Helvetica?

**Comment by dnl-blkv** [comment]
Thank you for the comment. Fixed in Version 1.1.0. Please see the new related issue: https://github.com/dnl-blkv/mcdowell-cv/issues/4

**Comment by tolribeiro** [comment]
Awesome! You're welcome Daniil, thank you for putting out such cool project. Keep up the good work, regards.
